name: cppdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - ninja
  - make
  #- gxx doesnt work for mac apple silicon
  - clangxx # added clangxx instead
  - doxygen
  - pip
  - pip:
    - breathe
    - sphinx
